# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c71f0b5183f0d328e9b37a88d1946e37ee81c53572a1425c2569fc1bd798ebab121e3d64f0918eed7373b854d46c9cb496d9a09531df1f72869a28d6ba3bd4de

test:
  secret_key_base: 7e2aed0e0efdf77023e34818e99279c15a65fda92faf68001bce73106e479f767cc81815541e88b767b6a665c168bebf2979671a227b97c6f31219bd9434d5fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
